#!/bin/bash

awk '
    function human(x) {
        if (x<1000) {return x} else {x/=1000}
        s="kMGTEPZY";
        while (x>=1000 && length(s)>1)
            {x/=1000; s=substr(s,2)}
        return int(x*10)/10 substr(s,1,1)
    }
    {printf "%s", human($1)}'
