#!/bin/bash

BATTERY_THRESHOLD_PATH="/sys/class/power_supply/BAT0/charge_control_end_threshold"
current_threshold=$(cat "$BATTERY_THRESHOLD_PATH")

if [[ $current_threshold -ne 100 ]]; then
    echo -ne '󱞜'
#else
    #echo -ne '󱟦'
fi

