#!/bin/bash

#define FC_API_KEY
. $CONFIG_DIR/panel_config.sh

PRICE=`curl -s "https://api.freecurrencyapi.com/v1/latest?apikey=$FC_API_KEY&currencies=EUR" | jq -r '.data.EUR'`
printf "%.3f $/€" "$PRICE"
